### ISSUE TITLE
Process exits immediately when cannot reach CloudWatch logs endpoint.

### ISSUE THREAD

**Issue by kiranmeduri** [aws/amazon-cloudwatch-logs-for-fluent-bit#18]
In the context of service-mesh setups like App Mesh, task or pod network is not ready to send external traffic until Envoy proxy is ready. This results in connect failures. Container launch ordering should probably work (could not find in documentation), but it is not currently possible in Kubernetes environment. 

To address, I would recommend this process to retry before giving up.

**Comment by PettitWesley** [comment]
Labelling this as a bug because it was not intended and it breaks workflows.

This happens because we try to create the log group when initializing the plugin. See [here](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/master/cloudwatch/cloudwatch.go#L141), and [here](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/master/fluent-bit-cloudwatch.go#L106).

Instead, we should do something like set a boolean on the OutputPlugin struct to track whether or not the log group has been created. Creation can be handled in [AddEvent()](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/master/cloudwatch/cloudwatch.go#L194) and Flush()- if creation is unsuccessful we can return a FLB_RETRY. Then Fluent Bit will not quit, and the creation and sending will be retried.

**Comment by kiranmeduri** [comment]
https://github.com/aws/aws-app-mesh-roadmap/issues/124
