### ISSUE TITLE
'log_retention_days' not getting picked up

### ISSUE THREAD

**Issue by g3kr** [aws/amazon-cloudwatch-logs-for-fluent-bit#237]
Hi,

We are running fluenbit daemonset on our EKS cluster with the below config. The `log_retention_days` property was recently added and I do not see the value being picked up after redeployment. It still shows '0'. Does this only work for newly created  cloudwatch log groups? We are using `amazon/aws-for-fluent-bit:latest` image.

```
[OUTPUT]
        Name              cloudwatch
        Match             kube.*
        region            ${AWS_REGION}
        log_group_name    eks-logs-${ENVIRONMENT}
        log_stream_prefix from-eks-fluentbit-
        log_retention_days 30 
        auto_create_group true 
```

**Comment by nielsvbrecht** [comment]
Have you created a role that is being assumed by the service account which has the proper policies attached?
The role needs to be able to set the log retention. 

I have deployed it, and it works for existing and new log groups. You will see that the pod is setting the log retention in the pod logs. Or otherwise you will see a permission denied log message.
