### ISSUE TITLE
Enable tagging created log groups

### ISSUE THREAD

**Issue by drboyer** [aws/amazon-cloudwatch-logs-for-fluent-bit#51]
Log groups can be tagged on creation (see [API reference](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogGroup.html)) - this can be helpful for cost allocation or other purposes. It may be convenient if this plugin could tag log groups that are created when the `auto_create_group` option is set to `true`.

The one wrinkle with implementing this is that I'm not sure exactly how well the fluent bit config file format works with embedded maps (since we'd likely have a config option like `log_group_tags` that would contain a map of tag key-values).

**Comment by hencrice** [comment]
Hey @drboyer thanks for the feedback!

Unfortunately, I think nested map is not one of the [supported configuration types](https://github.com/fluent/fluent-bit/blob/v1.4.2/include/fluent-bit/flb_config_map.h#L29). However, one way we can possibly get it to work is instead make it a list of comma separated strings like this:

```
[OUTPUT]
    log_group_tags tagName1=value1, tagName2=value2
```

Then in our plugin, we will need to use `=` as the separator for each string in the list in order to parse out the final key-value pair. Is that acceptable?

If you are ok with this, I'm going to cut an issue upstream to figure out whether this is a common use case that should be supported natively by Fluent Bit instead of in individual plugin.
